name: Générateur Mimolune [Bot]

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Thème de la comptine (laisser vide pour choix automatique)"
        required: false
        default: ""
  schedule:
    - cron: "17 4 * * *" # Décalé pour éviter le rush (06h17 Paris)
    - cron: "43 10 * * *" # Décalé pour éviter le rush (12h43 Paris)

jobs:
  build-and-generate-mimolune:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Cloner le dépôt
      uses: actions/checkout@v4

    - name: ⚙️ Installer FFmpeg (Moteur vidéo)
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: 🐍 Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 Installer les dépendances
      run: pip install -r requirements.txt

    - name: 🎬 Générer la comptine Mimolune
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        VIDEO_TOPIC: ${{ github.event.inputs.topic }}
      run: python main_kids.py

    - name: 💾 Sauvegarder la vidéo finale Mimolune
      uses: actions/upload-artifact@v4
      with:
        name: Video-Mimolune-Prete-${{ github.run_id }}
        path: assets/mimolune/final/final_short.mp4